#!/bin/bash
source ~/.dotfiles/colors.sh
ASPELL=$(which aspell)
if [ $? -ne 0 ]; then
    echo "Aspell not installed - unable to check spelling" >&2
    exit
else
    WORDS=$($ASPELL list < "$1")
fi
if [ -n "$WORDS" ]; then
    echo -e "${yellow}\tPossible spelling errors found in commit message. Use git commit --amend to change the message.\n\tPossible mispelled words: " $WORDS ".${default}" >&2
fi
git diff --cached --name-only | while read FILE; do
    # check des erreurs en PHP
    if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
        # Courtesy of swytsh from the comments below.
        if [[ -f $FILE ]]; then
            php -l "$FILE" 1> /dev/null
            if [ $? -ne 0 ]; then
                echo -e "${red}\tAborting commit due to files with syntax errors.${default}" >&2
                exit 1
            fi
        fi
    fi
done || exit $?
