#!/bin/bash
# pre-receive

source ~/.dotfiles/colors.sh

remote="$1"
url="$2"

echo $remote
echo $url
exit 1

read oldrev newrev ref
BRANCHE=`echo $ref | awk -F '/' '{print $3}'`
PART2=`echo $ref | awk -F '/' '{print $4}'`

echo $ref

echo $BRANCHE
echo $PART2

exit 1
if [ "$PART2" != "" ]; then
    BRANCHE=$BRANCHE"/"$PART2
fi

if [ "$BRANCHE" != "master" ]; then
    echo -e "${red}seule master peut etre déployée${default}"
    exit 1
fi

