#!/bin/bash
# pre-receive

source ~/.dotfiles/colors.sh

read oldrev newrev ref
BRANCHE=`echo $ref | awk -F '/' '{print $3}'`
PART2=`echo $ref | awk -F '/' '{print $4}'`
exit 1
if [ "$PART2" != "" ]; then
    BRANCHE=$BRANCHE"/"$PART2
fi

if [ "$BRANCHE" != "master" ]; then
    echo -e "${red}seule master peut etre déployée${default}"
    exit 1
fi

