#!/bin/sh
title=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 1 "title"|cut -b 44-|cut -d '"' -f 1|egrep -v ^$` 
STRLENGTH=$(echo -n $title | wc -m)
if [ "$STRLENGTH" -gt 25 ]; then
    title=$(echo $title | cut -c1-25)
    title="${title}…"
fi
artist=`dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'|egrep -A 2 "artist"|cut -b 20-|cut -d '"' -f 2|egrep -v ^$|egrep -v array|egrep -v artist`
if [ ! -z "$artist" -a ! -z "$title" ]; then
    echo $artist '|' $title
else
    echo ""
fi
